/**
 * Build-time default server.
 *
 * Generated by `scripts/export_contract.py` from the deployed server key, so the
 * napplet has a server to address before discovery answers. When the field is
 * empty the napplet relies on `cvmDiscover` and says so.
 */
import server from './contract/server.json';

export type ServerConfig = {
  pubkey: string;
  relays: string[];
};

export const DEFAULT_SERVER: ServerConfig = server as ServerConfig;

export function hasDefaultServer(): boolean {
  return typeof DEFAULT_SERVER.pubkey === 'string' && DEFAULT_SERVER.pubkey.length > 0;
}
